### ISSUE TITLE
Retain file extension and set mime-type

### ISSUE THREAD

**Issue by janjokela** [eventfuel/images-api#1]
Currently when an image gets uploaded, an image name is generated which doesn't include the filetype extension i.e. '.png' nor the mime-type gets set.

This means that when rendering rich text in iOS, the file cannot be rendered correctly.

**Comment by vascoorey** [comment]
Not much to add other than the behaviour has been validated. We don't do much in this chain other than render the HTML string (using a library) and store it for future presentation. When the UI sees a blob that it doesn't know for sure is an image it won't render it as such. I reckon adding the correct filetype to the url will fix it.

**Comment by janjokela** [comment]
The Niko smashed this 🐛
